# Generated by Django 3.2.9 on 2022-02-28 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usercustom'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.restaurante'),
        ),
    ]
