# Generated by Django 3.2.6 on 2022-03-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('app', '0003_usercustom_restaurante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCustom',
        ),
    ]
