# Generated by Django 3.2.9 on 2022-03-05 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220305_0618'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postulados8',
            new_name='Postulados',
        ),
    ]
