# Generated by Django 3.2.9 on 2022-03-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_postulados8_postulados'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='menu'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
