# Generated by Django 3.2.9 on 2022-04-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220307_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='hora_entrada',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='nit',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
