# Generated by Django 3.2.9 on 2022-04-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_restaurante_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='nit',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
