# Generated by Django 3.2.9 on 2022-04-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_restaurante_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesero',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='meseros'),
        ),
    ]
