# Generated by Django 3.2.9 on 2022-04-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_mesero_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesero',
            name='nombre2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
