# Generated by Django 3.2.9 on 2022-04-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='pago',
            field=models.IntegerField(max_length=50),
        ),
    ]
