# Generated by Django 3.2.9 on 2022-04-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_oferta_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='direccion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oferta',
            name='vacantes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oferta',
            name='pago',
            field=models.IntegerField(),
        ),
    ]
