# Generated by Django 3.2.9 on 2022-04-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20220410_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='telefono',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
