# Generated by Django 3.2.9 on 2022-04-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20220411_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
