# Generated by Django 3.2.9 on 2022-05-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_estado_hora_salida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesero',
            old_name='apellido1',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='mesero',
            old_name='apellido2',
            new_name='nombres',
        ),
        migrations.RemoveField(
            model_name='mesero',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='mesero',
            name='nombre1',
        ),
        migrations.RemoveField(
            model_name='mesero',
            name='nombre2',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='departamento',
        ),
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='estado',
            name='hora_salida',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mesas',
            name='estado',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(max_length=2),
        ),
    ]
