# Generated by Django 3.2.9 on 2022-06-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_factura_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
