# Generated by Django 3.2.9 on 2022-06-09 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_factura_fecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
