# Generated by Django 3.2.9 on 2022-06-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_oferta_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='nombre',
            field=models.TextField(),
        ),
    ]
